### ISSUE TITLE
Umbraco 8 version

### ISSUE THREAD

**Issue by levipadre** [OmarElSergany/Umbraco-Page-View-Counter-Optimized#1]
Hi,

Any chance you have this for Umbraco 8? I need exactly like this.
I'm happy to talk about paying for it, but it's really urgent. Please let me know.

Thanks!

**Comment by OmarElSergany** [comment]
Hi @levipadre 
                       Thank you for your interest.
I think it should work on Umbraco 8  but I never test it!
let me test it and back to you.

**Comment by levipadre** [comment]
Thanks! I have v8.2.1.

**Comment by OmarElSergany** [comment]
okay let's test it with v8.2.1.
I will back to you shortly

**Comment by OmarElSergany** [comment]
the plugin it self working fine the problem is the plugin installer

ApplicationEventHandler moved from Umbraco.Core and replaced with Composer & Components

I will Update the installer class and Porting package to V8

it may take up to 2 days if you can wait, if not you can download the package from 

[https://our.umbraco.com/packages/website-utilities/page-view-counter-optimized/](https://our.umbraco.com/packages/website-utilities/page-view-counter-optimized/)

and extract the zip file and copy the Reflections.UmbracoUtilities.dll to your bin folder

run the below sql  script against your database
[https://github.com/OmarElSergany/UmbracoPageViewCounter-Optimized/blob/master/Reflections.Umbraco.Utilities/PageViewCounter/Script.sql](https://github.com/OmarElSergany/UmbracoPageViewCounter-Optimized/blob/master/Reflections.Umbraco.Utilities/PageViewCounter/Script.sql)

and add this code to your template
  
﻿@{ 
    int nodeId = Umbraco.AssignedContentItem.Id;
    string cookieName = String.Format("PageView_{0}", nodeId);
    if (Session[cookieName] == null)
    {
        Reflections.UmbracoUtilities.PageViewCounter.SetPageViewCount(nodeId);
        Session[cookieName] = 1;
    }
}

@Reflections.UmbracoUtilities.PageViewCounter.GetPageViewCount(Umbraco.AssignedContentItem.Id)

**Comment by levipadre** [comment]
Thank you so much @OmarElSergany! I did as you described, but unfortunately I got server error when I open my site. Any idea what can cause?
```
Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Reflection.ReflectionTypeLoadException: Could not load all types from "Reflections.UmbracoUtilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.ApplicationEventHandler: Could not load type 'Umbraco.Core.ApplicationEventHandler' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

  at Umbraco.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a) in D:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 572
  at Umbraco.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter) in D:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 504
  at Umbraco.Core.Composing.TypeLoader.<>c__DisplayClass50_0`1.<GetTypes>b__1() in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 542
  at Umbraco.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 752
  at Umbraco.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 656
  at Umbraco.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 540
  at Umbraco.Core.Runtime.CoreRuntime.ResolveComposerTypes(TypeLoader typeLoader) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 275
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 149
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: Umbraco.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Reflection.ReflectionTypeLoadException: Could not load all types from "Reflections.UmbracoUtilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.ApplicationEventHandler: Could not load type 'Umbraco.Core.ApplicationEventHandler' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

  at Umbraco.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a) in D:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 572
  at Umbraco.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter) in D:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 504
  at Umbraco.Core.Composing.TypeLoader.<>c__DisplayClass50_0`1.<GetTypes>b__1() in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 542
  at Umbraco.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 752
  at Umbraco.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 656
  at Umbraco.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 540
  at Umbraco.Core.Runtime.CoreRuntime.ResolveComposerTypes(TypeLoader typeLoader) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 275
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 149
```

**Comment by OmarElSergany** [comment]
Sorry for that, Can you use below dll instead

[https://github.com/OmarElSergany/UmbracoPageViewCounter-Optimized/releases/tag/v1.0.0.1](https://github.com/OmarElSergany/UmbracoPageViewCounter-Optimized/releases/tag/v1.0.0.1)

I find out that this project used .NET Framework 4.8 not 4.7.2

**Comment by OmarElSergany** [comment]
okay it's ready for Umbraco 8 now!

39fb4ac271ea4c779684fce8ff9503f073422b1a

Will add the package to Umbraco packages and inform you once it's uploaded.

**Comment by levipadre** [comment]
Wow! It's super! Can't thank you enough! It works like a charm!
Last question.
How can I connect to a certain url? I have a download button which url's connect to a pdf in the Media section and I need to count the number of downloads (visits).
```
@{
var downloadableBrochure = Model.Value<IPublishedContent>("downloadableBrochure");
}
<a href="@(downloadableBrochure != null ? downloadableBrochure.Url : "")" target="_blank" download>Download Brochure</a>
```
I hope it's possible, that is the main point of this feature :)

**Comment by OmarElSergany** [comment]
You are most welcome!

this can be achieved with many ways you can use : 
 - Google Analytics goals and Google Tag Manager. (if you don't need to display the counter in front end.)
 - Using this plugin with some customization and some java scripts (only if you need to display the download counter in the front end). 

so do you need to display the download counter in the front end? or it's just for you and can get it from Google Analytics?

also I need to ask you (just out of curiosity) how much you usual pay to get packages like this one?

**Comment by levipadre** [comment]
I have an API endpoint which shows the data from your table:
```
[
    {
        "NodeId": 1166,
        "ViewsCounter": "2"
    },
    {
        "NodeId": 1171,
        "ViewsCounter": "1"
    }
]
```
and I set up a property which shows this`ViewsCounter` value in the backoffice. But at the moment it shows the pageview of the PAGE and not the BUTTON (download url) on the page.

And answering to you question, I think around $20-30.

**Comment by OmarElSergany** [comment]
No, I'll help with your project at no cost!
I just want to set up the package with extra feature and launch it on the market place and I need to know how much should I price it. (if decide not to publishing it as a free package).

Any way the easiest way to achieve that to make a new page and add java script to download the file 
and use the new page NodeId to get the number of downloads

**Comment by levipadre** [comment]
It's really kind of you! And yes, that is a good idea! Good luck with the selling if you decide to do so, I think it's a really good plugin.

I don't think this new page solution would work, but I need to think it through.
Just because in the backoffice I have these pages (development) and on each development pages there is this download brochure button. If I create dynamically a new page for every development page with the brochure file, I still need to know which page is connected to the actual development page. But maybe you are right, just need to think about it a bit :)

**Comment by OmarElSergany** [comment]
Thank you 😄 

for the above scenario
yes it can be done easily if you make it as a sub page (so page is connected to the actual development page - you can get the NodeId from child nodes) so when the user click the download button it's open new tab with the new page, and the new page will count the view and the java script will start the download and close the tab and in your back end  you will change the API to shows ViewsCounter for it's sub page.

but it's not the best practice 

I think the best way is to add a custom controller to handle the both counter and the download with a parameter with file url to the plugin, also add new table with node id, file URL and counter column; and you will need to change your API to get data from the new table

let me try and back to you

**Comment by levipadre** [comment]
Please try this custom controller, sounds more ideal ;)

**Comment by OmarElSergany** [comment]
@levipadre I Added a new issue for the download files counter

#2
